DROP TABLE IF EXISTS threat_scores;
DROP TABLE IF EXISTS metrics;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS alert_rules;
DROP TABLE IF EXISTS agents;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS organizations;
